head_canvas: |
  <link rel="apple-touch-icon" href="app-logo.png">
  <link rel="apple-touch-icon" sizes="180x180" href="app-logo.png">
  <link rel="shortcut icon" href="app-logo.png">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="apple-mobile-web-app-title" content="Ivan體檢">
